// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzsymezduwgqhjqckogh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6c3ltZXpkdXdncWhqcWNrb2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDI1MDMsImV4cCI6MjA2ODIxODUwM30.yu3597rOAv7dr7MZzJhtqOQPxlH6gpcglKDX0cC1jXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});